//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeEquipmentTag_EquipmentTag", "EquipmentTag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.EquipmentTag), "RecipeEquipmentTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeEquipmentTag), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeFoodGroup_FoodGroup", "FoodGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.FoodGroup), "RecipeFoodGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeFoodGroup), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeIngredient_Ingredient", "Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Ingredient), "RecipeIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeIngredient), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeEquipmentTag_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Recipe), "RecipeEquipmentTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeEquipmentTag), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeFoodGroup_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Recipe), "RecipeFoodGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeFoodGroup), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeIngredient_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Recipe), "RecipeIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeIngredient), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeStep_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Recipe), "RecipeStep", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeStep), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeTag_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Recipe), "RecipeTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeTag), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FoodFightSilverlightClient.Web.RecipeIngredient), "RecipeIngredient1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeIngredient), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeIngredient_State", "State", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FoodFightSilverlightClient.Web.State), "RecipeIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeIngredient), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeIngredient_Unit", "Unit", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(FoodFightSilverlightClient.Web.Unit), "RecipeIngredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeIngredient), true)]
[assembly: EdmRelationshipAttribute("FoodFightModel", "FK_RecipeTag_Tag", "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FoodFightSilverlightClient.Web.Tag), "RecipeTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FoodFightSilverlightClient.Web.RecipeTag), true)]

#endregion

namespace FoodFightSilverlightClient.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FoodFightEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FoodFightEntities object using the connection string found in the 'FoodFightEntities' section of the application configuration file.
        /// </summary>
        public FoodFightEntities() : base("name=FoodFightEntities", "FoodFightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FoodFightEntities object.
        /// </summary>
        public FoodFightEntities(string connectionString) : base(connectionString, "FoodFightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FoodFightEntities object.
        /// </summary>
        public FoodFightEntities(EntityConnection connection) : base(connection, "FoodFightEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EquipmentTag> EquipmentTags
        {
            get
            {
                if ((_EquipmentTags == null))
                {
                    _EquipmentTags = base.CreateObjectSet<EquipmentTag>("EquipmentTags");
                }
                return _EquipmentTags;
            }
        }
        private ObjectSet<EquipmentTag> _EquipmentTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodGroup> FoodGroups
        {
            get
            {
                if ((_FoodGroups == null))
                {
                    _FoodGroups = base.CreateObjectSet<FoodGroup>("FoodGroups");
                }
                return _FoodGroups;
            }
        }
        private ObjectSet<FoodGroup> _FoodGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipeEquipmentTag> RecipeEquipmentTags
        {
            get
            {
                if ((_RecipeEquipmentTags == null))
                {
                    _RecipeEquipmentTags = base.CreateObjectSet<RecipeEquipmentTag>("RecipeEquipmentTags");
                }
                return _RecipeEquipmentTags;
            }
        }
        private ObjectSet<RecipeEquipmentTag> _RecipeEquipmentTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipeFoodGroup> RecipeFoodGroups
        {
            get
            {
                if ((_RecipeFoodGroups == null))
                {
                    _RecipeFoodGroups = base.CreateObjectSet<RecipeFoodGroup>("RecipeFoodGroups");
                }
                return _RecipeFoodGroups;
            }
        }
        private ObjectSet<RecipeFoodGroup> _RecipeFoodGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipeIngredient> RecipeIngredients
        {
            get
            {
                if ((_RecipeIngredients == null))
                {
                    _RecipeIngredients = base.CreateObjectSet<RecipeIngredient>("RecipeIngredients");
                }
                return _RecipeIngredients;
            }
        }
        private ObjectSet<RecipeIngredient> _RecipeIngredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipeStep> RecipeSteps
        {
            get
            {
                if ((_RecipeSteps == null))
                {
                    _RecipeSteps = base.CreateObjectSet<RecipeStep>("RecipeSteps");
                }
                return _RecipeSteps;
            }
        }
        private ObjectSet<RecipeStep> _RecipeSteps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RecipeTag> RecipeTags
        {
            get
            {
                if ((_RecipeTags == null))
                {
                    _RecipeTags = base.CreateObjectSet<RecipeTag>("RecipeTags");
                }
                return _RecipeTags;
            }
        }
        private ObjectSet<RecipeTag> _RecipeTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<State> States
        {
            get
            {
                if ((_States == null))
                {
                    _States = base.CreateObjectSet<State>("States");
                }
                return _States;
            }
        }
        private ObjectSet<State> _States;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Unit> Units
        {
            get
            {
                if ((_Units == null))
                {
                    _Units = base.CreateObjectSet<Unit>("Units");
                }
                return _Units;
            }
        }
        private ObjectSet<Unit> _Units;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EquipmentTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipmentTags(EquipmentTag equipmentTag)
        {
            base.AddObject("EquipmentTags", equipmentTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodGroups(FoodGroup foodGroup)
        {
            base.AddObject("FoodGroups", foodGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipeEquipmentTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipeEquipmentTags(RecipeEquipmentTag recipeEquipmentTag)
        {
            base.AddObject("RecipeEquipmentTags", recipeEquipmentTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipeFoodGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipeFoodGroups(RecipeFoodGroup recipeFoodGroup)
        {
            base.AddObject("RecipeFoodGroups", recipeFoodGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipeIngredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipeIngredients(RecipeIngredient recipeIngredient)
        {
            base.AddObject("RecipeIngredients", recipeIngredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipeSteps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipeSteps(RecipeStep recipeStep)
        {
            base.AddObject("RecipeSteps", recipeStep);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RecipeTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipeTags(RecipeTag recipeTag)
        {
            base.AddObject("RecipeTags", recipeTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the States EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStates(State state)
        {
            base.AddObject("States", state);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Units EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUnits(Unit unit)
        {
            base.AddObject("Units", unit);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="EquipmentTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EquipmentTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EquipmentTag object.
        /// </summary>
        /// <param name="equipmentTagID">Initial value of the EquipmentTagID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static EquipmentTag CreateEquipmentTag(global::System.Int32 equipmentTagID, global::System.String name)
        {
            EquipmentTag equipmentTag = new EquipmentTag();
            equipmentTag.EquipmentTagID = equipmentTagID;
            equipmentTag.Name = name;
            return equipmentTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipmentTagID
        {
            get
            {
                return _EquipmentTagID;
            }
            set
            {
                if (_EquipmentTagID != value)
                {
                    OnEquipmentTagIDChanging(value);
                    ReportPropertyChanging("EquipmentTagID");
                    _EquipmentTagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EquipmentTagID");
                    OnEquipmentTagIDChanged();
                }
            }
        }
        private global::System.Int32 _EquipmentTagID;
        partial void OnEquipmentTagIDChanging(global::System.Int32 value);
        partial void OnEquipmentTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeEquipmentTag_EquipmentTag", "RecipeEquipmentTag")]
        public EntityCollection<RecipeEquipmentTag> RecipeEquipmentTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeEquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_EquipmentTag", "RecipeEquipmentTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeEquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_EquipmentTag", "RecipeEquipmentTag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="FoodGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodGroup object.
        /// </summary>
        /// <param name="foodGroupID">Initial value of the FoodGroupID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static FoodGroup CreateFoodGroup(global::System.Int32 foodGroupID, global::System.String name)
        {
            FoodGroup foodGroup = new FoodGroup();
            foodGroup.FoodGroupID = foodGroupID;
            foodGroup.Name = name;
            return foodGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodGroupID
        {
            get
            {
                return _FoodGroupID;
            }
            set
            {
                if (_FoodGroupID != value)
                {
                    OnFoodGroupIDChanging(value);
                    ReportPropertyChanging("FoodGroupID");
                    _FoodGroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FoodGroupID");
                    OnFoodGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _FoodGroupID;
        partial void OnFoodGroupIDChanging(global::System.Int32 value);
        partial void OnFoodGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeFoodGroup_FoodGroup", "RecipeFoodGroup")]
        public EntityCollection<RecipeFoodGroup> RecipeFoodGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeFoodGroup>("FoodFightModel.FK_RecipeFoodGroup_FoodGroup", "RecipeFoodGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeFoodGroup>("FoodFightModel.FK_RecipeFoodGroup_FoodGroup", "RecipeFoodGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="ingredientID">Initial value of the IngredientID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 ingredientID, global::System.String name)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.IngredientID = ingredientID;
            ingredient.Name = name;
            return ingredient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientID
        {
            get
            {
                return _IngredientID;
            }
            set
            {
                if (_IngredientID != value)
                {
                    OnIngredientIDChanging(value);
                    ReportPropertyChanging("IngredientID");
                    _IngredientID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IngredientID");
                    OnIngredientIDChanged();
                }
            }
        }
        private global::System.Int32 _IngredientID;
        partial void OnIngredientIDChanging(global::System.Int32 value);
        partial void OnIngredientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_Ingredient", "RecipeIngredient")]
        public EntityCollection<RecipeIngredient> RecipeIngredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_Ingredient", "RecipeIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_Ingredient", "RecipeIngredient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="serves">Initial value of the Serves property.</param>
        public static Recipe CreateRecipe(global::System.Int32 recipeID, global::System.String name, global::System.Int32 serves)
        {
            Recipe recipe = new Recipe();
            recipe.RecipeID = recipeID;
            recipe.Name = name;
            recipe.Serves = serves;
            return recipe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                if (_RecipeID != value)
                {
                    OnRecipeIDChanging(value);
                    ReportPropertyChanging("RecipeID");
                    _RecipeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeID");
                    OnRecipeIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> CookingTime
        {
            get
            {
                return _CookingTime;
            }
            set
            {
                OnCookingTimeChanging(value);
                ReportPropertyChanging("CookingTime");
                _CookingTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CookingTime");
                OnCookingTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _CookingTime;
        partial void OnCookingTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnCookingTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Serves
        {
            get
            {
                return _Serves;
            }
            set
            {
                OnServesChanging(value);
                ReportPropertyChanging("Serves");
                _Serves = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Serves");
                OnServesChanged();
            }
        }
        private global::System.Int32 _Serves;
        partial void OnServesChanging(global::System.Int32 value);
        partial void OnServesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Picture
        {
            get
            {
                return StructuralObject.GetValidValue(_Picture);
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.Byte[] _Picture;
        partial void OnPictureChanging(global::System.Byte[] value);
        partial void OnPictureChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeEquipmentTag_Recipe", "RecipeEquipmentTag")]
        public EntityCollection<RecipeEquipmentTag> RecipeEquipmentTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeEquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_Recipe", "RecipeEquipmentTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeEquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_Recipe", "RecipeEquipmentTag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeFoodGroup_Recipe", "RecipeFoodGroup")]
        public EntityCollection<RecipeFoodGroup> RecipeFoodGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeFoodGroup>("FoodFightModel.FK_RecipeFoodGroup_Recipe", "RecipeFoodGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeFoodGroup>("FoodFightModel.FK_RecipeFoodGroup_Recipe", "RecipeFoodGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_Recipe", "RecipeIngredient")]
        public EntityCollection<RecipeIngredient> RecipeIngredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_Recipe", "RecipeIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_Recipe", "RecipeIngredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeStep_Recipe", "RecipeStep")]
        public EntityCollection<RecipeStep> RecipeSteps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeStep>("FoodFightModel.FK_RecipeStep_Recipe", "RecipeStep");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeStep>("FoodFightModel.FK_RecipeStep_Recipe", "RecipeStep", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeTag_Recipe", "RecipeTag")]
        public EntityCollection<RecipeTag> RecipeTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeTag>("FoodFightModel.FK_RecipeTag_Recipe", "RecipeTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeTag>("FoodFightModel.FK_RecipeTag_Recipe", "RecipeTag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="RecipeEquipmentTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipeEquipmentTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipeEquipmentTag object.
        /// </summary>
        /// <param name="recipeEquipmentTagID">Initial value of the RecipeEquipmentTagID property.</param>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="equipmentTagID">Initial value of the EquipmentTagID property.</param>
        public static RecipeEquipmentTag CreateRecipeEquipmentTag(global::System.Int32 recipeEquipmentTagID, global::System.Int32 recipeID, global::System.Int32 equipmentTagID)
        {
            RecipeEquipmentTag recipeEquipmentTag = new RecipeEquipmentTag();
            recipeEquipmentTag.RecipeEquipmentTagID = recipeEquipmentTagID;
            recipeEquipmentTag.RecipeID = recipeID;
            recipeEquipmentTag.EquipmentTagID = equipmentTagID;
            return recipeEquipmentTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeEquipmentTagID
        {
            get
            {
                return _RecipeEquipmentTagID;
            }
            set
            {
                if (_RecipeEquipmentTagID != value)
                {
                    OnRecipeEquipmentTagIDChanging(value);
                    ReportPropertyChanging("RecipeEquipmentTagID");
                    _RecipeEquipmentTagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeEquipmentTagID");
                    OnRecipeEquipmentTagIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeEquipmentTagID;
        partial void OnRecipeEquipmentTagIDChanging(global::System.Int32 value);
        partial void OnRecipeEquipmentTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                OnRecipeIDChanging(value);
                ReportPropertyChanging("RecipeID");
                _RecipeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeID");
                OnRecipeIDChanged();
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipmentTagID
        {
            get
            {
                return _EquipmentTagID;
            }
            set
            {
                OnEquipmentTagIDChanging(value);
                ReportPropertyChanging("EquipmentTagID");
                _EquipmentTagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentTagID");
                OnEquipmentTagIDChanged();
            }
        }
        private global::System.Int32 _EquipmentTagID;
        partial void OnEquipmentTagIDChanging(global::System.Int32 value);
        partial void OnEquipmentTagIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeEquipmentTag_EquipmentTag", "EquipmentTag")]
        public EquipmentTag EquipmentTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_EquipmentTag", "EquipmentTag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_EquipmentTag", "EquipmentTag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EquipmentTag> EquipmentTagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_EquipmentTag", "EquipmentTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EquipmentTag>("FoodFightModel.FK_RecipeEquipmentTag_EquipmentTag", "EquipmentTag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeEquipmentTag_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeEquipmentTag_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeEquipmentTag_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeEquipmentTag_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("FoodFightModel.FK_RecipeEquipmentTag_Recipe", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="RecipeFoodGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipeFoodGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipeFoodGroup object.
        /// </summary>
        /// <param name="recipeFoodGroupID">Initial value of the RecipeFoodGroupID property.</param>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="foodGroupID">Initial value of the FoodGroupID property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        public static RecipeFoodGroup CreateRecipeFoodGroup(global::System.Int32 recipeFoodGroupID, global::System.Int32 recipeID, global::System.Int32 foodGroupID, global::System.Decimal amount)
        {
            RecipeFoodGroup recipeFoodGroup = new RecipeFoodGroup();
            recipeFoodGroup.RecipeFoodGroupID = recipeFoodGroupID;
            recipeFoodGroup.RecipeID = recipeID;
            recipeFoodGroup.FoodGroupID = foodGroupID;
            recipeFoodGroup.Amount = amount;
            return recipeFoodGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeFoodGroupID
        {
            get
            {
                return _RecipeFoodGroupID;
            }
            set
            {
                if (_RecipeFoodGroupID != value)
                {
                    OnRecipeFoodGroupIDChanging(value);
                    ReportPropertyChanging("RecipeFoodGroupID");
                    _RecipeFoodGroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeFoodGroupID");
                    OnRecipeFoodGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeFoodGroupID;
        partial void OnRecipeFoodGroupIDChanging(global::System.Int32 value);
        partial void OnRecipeFoodGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                OnRecipeIDChanging(value);
                ReportPropertyChanging("RecipeID");
                _RecipeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeID");
                OnRecipeIDChanged();
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodGroupID
        {
            get
            {
                return _FoodGroupID;
            }
            set
            {
                OnFoodGroupIDChanging(value);
                ReportPropertyChanging("FoodGroupID");
                _FoodGroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FoodGroupID");
                OnFoodGroupIDChanged();
            }
        }
        private global::System.Int32 _FoodGroupID;
        partial void OnFoodGroupIDChanging(global::System.Int32 value);
        partial void OnFoodGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeFoodGroup_FoodGroup", "FoodGroup")]
        public FoodGroup FoodGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodGroup>("FoodFightModel.FK_RecipeFoodGroup_FoodGroup", "FoodGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodGroup>("FoodFightModel.FK_RecipeFoodGroup_FoodGroup", "FoodGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FoodGroup> FoodGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FoodGroup>("FoodFightModel.FK_RecipeFoodGroup_FoodGroup", "FoodGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FoodGroup>("FoodFightModel.FK_RecipeFoodGroup_FoodGroup", "FoodGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeFoodGroup_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeFoodGroup_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeFoodGroup_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeFoodGroup_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("FoodFightModel.FK_RecipeFoodGroup_Recipe", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="RecipeIngredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipeIngredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipeIngredient object.
        /// </summary>
        /// <param name="recipeIngredientID">Initial value of the RecipeIngredientID property.</param>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="ingredientID">Initial value of the IngredientID property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        public static RecipeIngredient CreateRecipeIngredient(global::System.Int32 recipeIngredientID, global::System.Int32 recipeID, global::System.Int32 ingredientID, global::System.Decimal amount)
        {
            RecipeIngredient recipeIngredient = new RecipeIngredient();
            recipeIngredient.RecipeIngredientID = recipeIngredientID;
            recipeIngredient.RecipeID = recipeID;
            recipeIngredient.IngredientID = ingredientID;
            recipeIngredient.Amount = amount;
            return recipeIngredient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeIngredientID
        {
            get
            {
                return _RecipeIngredientID;
            }
            set
            {
                if (_RecipeIngredientID != value)
                {
                    OnRecipeIngredientIDChanging(value);
                    ReportPropertyChanging("RecipeIngredientID");
                    _RecipeIngredientID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeIngredientID");
                    OnRecipeIngredientIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeIngredientID;
        partial void OnRecipeIngredientIDChanging(global::System.Int32 value);
        partial void OnRecipeIngredientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                OnRecipeIDChanging(value);
                ReportPropertyChanging("RecipeID");
                _RecipeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeID");
                OnRecipeIDChanged();
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientID
        {
            get
            {
                return _IngredientID;
            }
            set
            {
                OnIngredientIDChanging(value);
                ReportPropertyChanging("IngredientID");
                _IngredientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IngredientID");
                OnIngredientIDChanged();
            }
        }
        private global::System.Int32 _IngredientID;
        partial void OnIngredientIDChanging(global::System.Int32 value);
        partial void OnIngredientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StateID
        {
            get
            {
                return _StateID;
            }
            set
            {
                OnStateIDChanging(value);
                ReportPropertyChanging("StateID");
                _StateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateID");
                OnStateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StateID;
        partial void OnStateIDChanging(Nullable<global::System.Int32> value);
        partial void OnStateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitID
        {
            get
            {
                return _UnitID;
            }
            set
            {
                OnUnitIDChanging(value);
                ReportPropertyChanging("UnitID");
                _UnitID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitID");
                OnUnitIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitID;
        partial void OnUnitIDChanging(Nullable<global::System.Int32> value);
        partial void OnUnitIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AliasForRecipeIngredientID
        {
            get
            {
                return _AliasForRecipeIngredientID;
            }
            set
            {
                OnAliasForRecipeIngredientIDChanging(value);
                ReportPropertyChanging("AliasForRecipeIngredientID");
                _AliasForRecipeIngredientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AliasForRecipeIngredientID");
                OnAliasForRecipeIngredientIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AliasForRecipeIngredientID;
        partial void OnAliasForRecipeIngredientIDChanging(Nullable<global::System.Int32> value);
        partial void OnAliasForRecipeIngredientIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_Ingredient", "Ingredient")]
        public Ingredient Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("FoodFightModel.FK_RecipeIngredient_Ingredient", "Ingredient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("FoodFightModel.FK_RecipeIngredient_Ingredient", "Ingredient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingredient> IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("FoodFightModel.FK_RecipeIngredient_Ingredient", "Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingredient>("FoodFightModel.FK_RecipeIngredient_Ingredient", "Ingredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeIngredient_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeIngredient_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeIngredient_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("FoodFightModel.FK_RecipeIngredient_Recipe", "Recipe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient1")]
        public EntityCollection<RecipeIngredient> RecipeIngredient1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient")]
        public RecipeIngredient RecipeIngredient2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RecipeIngredient> RecipeIngredient2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_RecipeIngredient", "RecipeIngredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_State", "State")]
        public State State
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("FoodFightModel.FK_RecipeIngredient_State", "State").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("FoodFightModel.FK_RecipeIngredient_State", "State").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<State> StateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("FoodFightModel.FK_RecipeIngredient_State", "State");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<State>("FoodFightModel.FK_RecipeIngredient_State", "State", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_Unit", "Unit")]
        public Unit Unit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("FoodFightModel.FK_RecipeIngredient_Unit", "Unit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("FoodFightModel.FK_RecipeIngredient_Unit", "Unit").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Unit> UnitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Unit>("FoodFightModel.FK_RecipeIngredient_Unit", "Unit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Unit>("FoodFightModel.FK_RecipeIngredient_Unit", "Unit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="RecipeStep")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipeStep : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipeStep object.
        /// </summary>
        /// <param name="recipeStepID">Initial value of the RecipeStepID property.</param>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="stepNumber">Initial value of the StepNumber property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static RecipeStep CreateRecipeStep(global::System.Int32 recipeStepID, global::System.Int32 recipeID, global::System.Int32 stepNumber, global::System.String description)
        {
            RecipeStep recipeStep = new RecipeStep();
            recipeStep.RecipeStepID = recipeStepID;
            recipeStep.RecipeID = recipeID;
            recipeStep.StepNumber = stepNumber;
            recipeStep.Description = description;
            return recipeStep;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeStepID
        {
            get
            {
                return _RecipeStepID;
            }
            set
            {
                if (_RecipeStepID != value)
                {
                    OnRecipeStepIDChanging(value);
                    ReportPropertyChanging("RecipeStepID");
                    _RecipeStepID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeStepID");
                    OnRecipeStepIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeStepID;
        partial void OnRecipeStepIDChanging(global::System.Int32 value);
        partial void OnRecipeStepIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                OnRecipeIDChanging(value);
                ReportPropertyChanging("RecipeID");
                _RecipeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeID");
                OnRecipeIDChanged();
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StepNumber
        {
            get
            {
                return _StepNumber;
            }
            set
            {
                OnStepNumberChanging(value);
                ReportPropertyChanging("StepNumber");
                _StepNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StepNumber");
                OnStepNumberChanged();
            }
        }
        private global::System.Int32 _StepNumber;
        partial void OnStepNumberChanging(global::System.Int32 value);
        partial void OnStepNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Picture
        {
            get
            {
                return StructuralObject.GetValidValue(_Picture);
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.Byte[] _Picture;
        partial void OnPictureChanging(global::System.Byte[] value);
        partial void OnPictureChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeStep_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeStep_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeStep_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeStep_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("FoodFightModel.FK_RecipeStep_Recipe", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="RecipeTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RecipeTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RecipeTag object.
        /// </summary>
        /// <param name="recipeTagID">Initial value of the RecipeTagID property.</param>
        /// <param name="recipeID">Initial value of the RecipeID property.</param>
        /// <param name="tagID">Initial value of the TagID property.</param>
        public static RecipeTag CreateRecipeTag(global::System.Int32 recipeTagID, global::System.Int32 recipeID, global::System.Int32 tagID)
        {
            RecipeTag recipeTag = new RecipeTag();
            recipeTag.RecipeTagID = recipeTagID;
            recipeTag.RecipeID = recipeID;
            recipeTag.TagID = tagID;
            return recipeTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeTagID
        {
            get
            {
                return _RecipeTagID;
            }
            set
            {
                if (_RecipeTagID != value)
                {
                    OnRecipeTagIDChanging(value);
                    ReportPropertyChanging("RecipeTagID");
                    _RecipeTagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeTagID");
                    OnRecipeTagIDChanged();
                }
            }
        }
        private global::System.Int32 _RecipeTagID;
        partial void OnRecipeTagIDChanging(global::System.Int32 value);
        partial void OnRecipeTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeID
        {
            get
            {
                return _RecipeID;
            }
            set
            {
                OnRecipeIDChanging(value);
                ReportPropertyChanging("RecipeID");
                _RecipeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipeID");
                OnRecipeIDChanged();
            }
        }
        private global::System.Int32 _RecipeID;
        partial void OnRecipeIDChanging(global::System.Int32 value);
        partial void OnRecipeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                OnTagIDChanging(value);
                ReportPropertyChanging("TagID");
                _TagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TagID");
                OnTagIDChanged();
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeTag_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeTag_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeTag_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("FoodFightModel.FK_RecipeTag_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("FoodFightModel.FK_RecipeTag_Recipe", "Recipe", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeTag_Tag", "Tag")]
        public Tag Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("FoodFightModel.FK_RecipeTag_Tag", "Tag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("FoodFightModel.FK_RecipeTag_Tag", "Tag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tag> TagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("FoodFightModel.FK_RecipeTag_Tag", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tag>("FoodFightModel.FK_RecipeTag_Tag", "Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="State")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class State : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new State object.
        /// </summary>
        /// <param name="stateID">Initial value of the StateID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static State CreateState(global::System.Int32 stateID, global::System.String description)
        {
            State state = new State();
            state.StateID = stateID;
            state.Description = description;
            return state;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StateID
        {
            get
            {
                return _StateID;
            }
            set
            {
                if (_StateID != value)
                {
                    OnStateIDChanging(value);
                    ReportPropertyChanging("StateID");
                    _StateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StateID");
                    OnStateIDChanged();
                }
            }
        }
        private global::System.Int32 _StateID;
        partial void OnStateIDChanging(global::System.Int32 value);
        partial void OnStateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_State", "RecipeIngredient")]
        public EntityCollection<RecipeIngredient> RecipeIngredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_State", "RecipeIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_State", "RecipeIngredient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagID">Initial value of the TagID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Tag CreateTag(global::System.Int32 tagID, global::System.String name)
        {
            Tag tag = new Tag();
            tag.TagID = tagID;
            tag.Name = name;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                if (_TagID != value)
                {
                    OnTagIDChanging(value);
                    ReportPropertyChanging("TagID");
                    _TagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagID");
                    OnTagIDChanged();
                }
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeTag_Tag", "RecipeTag")]
        public EntityCollection<RecipeTag> RecipeTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeTag>("FoodFightModel.FK_RecipeTag_Tag", "RecipeTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeTag>("FoodFightModel.FK_RecipeTag_Tag", "RecipeTag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FoodFightModel", Name="Unit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Unit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Unit object.
        /// </summary>
        /// <param name="unitID">Initial value of the UnitID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Unit CreateUnit(global::System.Int32 unitID, global::System.String name)
        {
            Unit unit = new Unit();
            unit.UnitID = unitID;
            unit.Name = name;
            return unit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnitID
        {
            get
            {
                return _UnitID;
            }
            set
            {
                if (_UnitID != value)
                {
                    OnUnitIDChanging(value);
                    ReportPropertyChanging("UnitID");
                    _UnitID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UnitID");
                    OnUnitIDChanged();
                }
            }
        }
        private global::System.Int32 _UnitID;
        partial void OnUnitIDChanging(global::System.Int32 value);
        partial void OnUnitIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FoodFightModel", "FK_RecipeIngredient_Unit", "RecipeIngredient")]
        public EntityCollection<RecipeIngredient> RecipeIngredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_Unit", "RecipeIngredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RecipeIngredient>("FoodFightModel.FK_RecipeIngredient_Unit", "RecipeIngredient", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
